import Head from "next/head";
import { PROJECTS } from "@/js/constants";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs Projects</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            My {PROJECTS.length} projects based on&nbsp;
            <code className={styles.code}>Next.js</code>
          </p>
        </div>

        <div className={styles.center}>
          <span className={styles.name}>By Lucy Shuai</span>
        </div>

        <div className={styles.grid}>
          {PROJECTS.map((p) => (
            <Link
              href={p.href}
              className={styles.card}
              rel='noopener noreferrer'
            >
              <h2 className={inter.className}>
                {p.name} <span>-&gt;</span>
              </h2>
              <p className={inter.className}>{p.desc}</p>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
